version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: weekly
    groups:
      next-react:
        patterns: ["next", "eslint-config-next", "react", "react-dom", "@types/react", "@types/react-dom"]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
